name: serilog-logging-test

services:
  elasticsearch:
    image: elasticsearch:7.17.5
    container_name: es-container
    environment:
      - xpack.security.enabled=false
      - node.name=es-container
      - discovery.type=single-node
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - es-network

  kibana:
    image: kibana:7.17.5
    container_name: kb-container
    environment:
      ELASTICSEARCH_HOSTS: http://es-container:9200
    ports:
      - 5601:5601
    networks:
      - es-network
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana-data:/usr/share/kibana/data

volumes:
  es-data:
    driver: local
  kibana-data:
    driver: local

networks:
  es-network:
    driver: bridge